import '../styles/index.css';
import '../styles/index.scss';
import type { Metadata } from 'next'
import { Playfair_Display } from 'next/font/google';
import Footer from '@/components/footer';
import Header from '@/components/header';

const playfair_display = Playfair_Display({ subsets: ['vietnamese'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={playfair_display.className} >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
